server:
  port: 8999
spring:
  application:
    name: mybatis-demo
  datasource:
    url: jdbc:mysql://localhost:3306/dhb?serverTimezone=UTC
    password: 12345
    username: root
  aop:
    proxy-target-class: false
  data:
    solr:
      host: http://locahost:8983/solr
mybatis:
  config-location: classpath:mybatis-spring-config.xml
  mapper-locations: classpath:mapper/UserMapper.xml